/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "MainTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
